include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - linux/**
    - macos/**
    - web/**
    - windows/**

linter:
  rules:
    public_member_api_docs: true
    unawaited_futures: true
